#!/bin/bash
app="$1"
id=$RANDOM
id2username(){
echo $1.sandbox
}
id_usr=$(id2username $id)
me=$(whoami)

[ -d sandboxs ] || exit
chmod 700 sandboxs || exit
cd sandboxs || exit
root="$PWD"
[ -d data ] || exit
chmod 700 data || exit
[ -d bin ] || exit
chmod 700 bin || exit
[ -d uninstall ] || exit
chmod 700 uninstall || exit

cd "$root/data" || exit
mkdir $id || exit
chmod 770 $id || exit
sudo useradd --home="$PWD/$id" --shell /bin/false --user-group $id_usr || exit
sudo chown $me:$id_usr $id || exit
[ ! -f /etc/sudoers.d/$id_usr ] || exit
sudo sh -c "echo '$me ALL=($id_usr) NOPASSWD: ALL' > /etc/sudoers.d/$id_usr" || exit
[ -f /etc/sudoers.d/$id_usr ] || exit

[ ! -f "$root/bin/$app" ] || exit
echo "#!/bin/sh
xhost si:localuser:$id_usr
sudo -u $id_usr '$app' \"\$@\"
" > "$root/bin/$app"
[ -f "$root/bin/$app" ] || exit
chmod +x "$root/bin/$app"

[ ! -f "$root/uninstall/$app" ] || exit
echo "#!/bin/sh
sudo userdel $id_usr || exit
sudo rm -fr '/etc/sudoers.d/$id_usr' '$root/data/$id' '$root/bin/$app' \"\$0\"
" > "$root/uninstall/$app"
[ -f "$root/uninstall/$app" ] || exit
chmod +x "$root/uninstall/$app"
